_this addAction ["Teleport - 3ID Headquarters","scripts\teleport.sqf",["hq"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - AT","scripts\teleport.sqf",["attp"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Base","scripts\teleport.sqf",["basetp"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Grenade Range","scripts\teleport.sqf",["rt_2"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - M16A2 (Rifle)","scripts\teleport.sqf",["M16TP"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - M203","scripts\teleport.sqf",["M203tp"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - M249","scripts\teleport.sqf",["mguntp"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - M17","scripts\teleport.sqf",["M17TP"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Medical Field","scripts\teleport.sqf",["medicbay"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Obstacle Course","scripts\teleport.sqf",["oc"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Cottrell Field","scripts\teleport.sqf",["cf"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Sniper Range","scripts\teleport.sqf",["Snipe"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Training Field","scripts\teleport.sqf",["ait"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Barracks","scripts\teleport.sqf",["Barracks"],1.5,true,true,"","true",5,false,"",""];
_this addAction ["Teleport - Motor Pool","scripts\teleport.sqf",["MP"],1.5,true,true,"","true",5,false,"",""];