//Automatic Rifleman Loadout
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
player addBackpack "rhsusf_assault_eagleaiii_ocp";
player addItemToBackpack "rhsusf_100Rnd_556x45_soft_pouch";
player addWeapon "rhs_weap_m249_pip_L";
player addPrimaryWeaponItem "RH_peq15";
removeBackpack player;
player forceAddUniform "rhs_uniform_cu_ocp";
for "_i" from 1 to 8 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_Flashlight_MX991";
player addItemToUniform "ACE_EarPlugs";
player addVest "rhsusf_iotv_ocp_SAW";
player addItemToVest "rhsusf_ANPVS_14";
for "_i" from 1 to 2 do {player addItemToVest "rhsusf_200Rnd_556x45_soft_pouch";};
for "_i" from 1 to 2 do {player addItemToVest "rhs_mag_an_m8hc";};
player addHeadgear "rhsusf_ach_helmet_headset_ocp";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";

player setSpeaker "ACE_NoVoice";
