//Platoon Leader
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
player forceAddUniform "rhs_uniform_cu_ocp";
player addBackpack "rhsusf_assault_eagleaiii_ocp";
player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer";
player addItemToBackpack "rhsusf_mag_15Rnd_9x19_FMJ";
player addWeapon "rhs_weap_m4a1_carryhandle";
player addWeapon "rhsusf_weap_m9";
removeBackpack player;
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
player addVest "rhsusf_iotv_ocp_Squadleader";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 8 do {player addItemToUniform "ACE_packingBandage";};
player addItemToUniform "ItemcTabHCam";
player addItemToUniform "ACE_MapTools";
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_Flashlight_MX991";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {player addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
for "_i" from 1 to 4 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer";};
for "_i" from 1 to 2 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {player addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 2 do {player addItemToVest "B_IR_Grenade";};
player addItemToVest "SmokeShellYellow";
player addItemToVest "SmokeShellPurple";
player addItemToVest "SmokeShellBlue";
player addItemToVest "rhsusf_ANPVS_15";
player addHeadgear "rhsusf_ach_helmet_ocp";
player addWeapon "Rangefinder";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
pplayer linkItem "ItemcTab";
player setSpeaker "ACE_NoVoice";
